import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [loginDetails, setLoginDetails] = useState({
    email: '',
    password: '',
  })

  const handleInput = (event) => {
    let value = event.target.value;
    let name = event.target.name;

    setLoginDetails({...loginDetails, [name]: value })
  }

  const handleLogin = async (event) => {
    event.preventDefault();

    await fetch('/api/login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      }, 
      body: JSON.stringify(loginDetails)
    }).then((result) => {

    })

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleLogin}> 
          <input name='email' type='email' onChange={handleInput} value={loginDetails.email} placeholder='EMAIL' />
          <input name='password' type='password' onChange={handleInput} value={loginDetails.password} placeholder='PASSWORD' />
          <input type='submit' value='LOGIN' />
        </form>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
